- name: Create TLS Secrets
  gather_facts: no
  hosts: localhost
  tasks:
    - name: Call tls-secrets Role
      ansible.builtin.include_role:
        name: tls-secrets
      loop: "{{ tls_secrets[cluster_name] }}"
      loop_control:
        loop_var: tls_secret
